= Zadani 

Zadáním bakalářské práce je vytvoření výpočetního clusteru, který bude řízen za pomoci kubernetes.
Jednotlivé nody, které budou specifikovány v daném souboru budou moci být přidány a odebrány dle potřeby.
Tyto výpočetní nody budou mít nainstalovaný linuxový operační systém a budou zajistěné fakultou. 
Nody se budou přípravovat pomocí technologií ansible, která usnadní konfiguraci nodů.
Na tomto vytvořeném clusteru dále bude spuštěno lámání hesel. 
A to takovým způsobem, že master node bude předávat práci workerům. Ty budou následně 
ve vytvořeném docker containeru crackovat přidělenou práci a vrátí mastru výsledky crackování. 
O crackování se bude starat software jménem hashcat, který může být optimalizovaný i na grafické karty.
Budou se crackovat zejména sha1 hashe a to pomocí bruteforce útoků, slovníkových útoků a útoků s maskou.
Výkonost jednotlivých metod na crackování následně bude porovnána a její rychlost analyzována.

== Práce bý měla zahrnovat

. Popis a analýza použitých technologií ( kubernetes, ansible, docker, hashcat )
. Vytvoření a popis sestaveného clusteru
. Popis různých útoků a analýza nejčastěji používaných hesel
. Spostění softwaru s různými metody útoku ( bruteforce, slovíkový, mask )
. Analýza výsledku rychlosti crackování

