apiVersion: apps/v1
kind: Deployment 
metadata:
  name: private 
spec:
  selector:
    matchLabels:
      run: private
  replicas: 1
  template:
    metadata:
      labels:
        run: private 
    spec:
      hostname: private-pod
      subdomain: privateservice
      containers:
      - name: private 
        image: klastom1/privateservice
        ports:
        - containerPort: 8081

