apiVersion: v1
kind: Service
metadata:
  name: password-recovery-privateservice
  labels:
    run: privateservice 
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    run: privateservice 
