- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address="192.168.122.122" --node-name pod1 --pod-network-cidr=192.168.0.0/16 


- name: Copy and setup directories for K8s configs.
  shell: |
   mkdir -p $HOME/.kube
   sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
   sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: Install calico pod network
  become: false
  command: kubectl apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"


